---
- hosts: node1
  tasks:
  - name: check mariadn status
    command: /usr/bin/systemctl is-active mariadb
    ignore_errors: yes
    register: results

  - name: install httpd
    yum: 
      name: httpd
      state: latest
    when: results.rc == 0

  - name: start httpd
    service:
      name: httpd
      state: stopped
