--- 
- 
  hosts: node1
  name: "simple playbook"
  tasks: 
    - 
      name: "install vsftpd"
      yum: vsftpd
    - 
      name: "enable vsftpd"
      service: "name=vsftpd enable=true"
    - 
      copy: 
        content: "welcome to vsftpd"
        dest: /var/ftp/pub/README
        force: false
        mode: 36
      name: "create read me file"
